namespace Ahed_project.MasterData
{
    public enum ProjectMethods
    {
        CREATE,
        GET,
        UPDATE,
        LOGIN,
        AUTH,
        GET_PROJECTS,
        GET_PRODUCTS,
        GET_PRODUCT,
        GET_PRODUCT_CALCULATIONS,
        GET_MATERIALS,
        GET_GEOMETRIES,
        CALCULATE,
        CALCULATE_TEMPERATURE,
        CALCULATE_PRESSURE,
        CREATE_CALCULATION,
        UPDATE_CHOOSE,
        UPDATE_CALCULATION,
        CALCULATE_GEOMETRY,
        GET_TAB_STATE,
        SET_TAB_STATE,
        CALCULATE_BAFFLE,
        GET_GEOMETRY,
        GET_BAFFLE,
        GET_OVERALL,
        CALCULATE_OVERALL,
        DELETE_PROJECT,
        DELETE_CALCULATION,
        COPY_CALCULATION
    }
}
